
package servico;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CalcularMediaImplService", targetNamespace = "http://servico/", wsdlLocation = "http://localhost:8080/servico/?wsdl")
public class CalcularMediaImplService
    extends Service
{

    private final static URL CALCULARMEDIAIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException CALCULARMEDIAIMPLSERVICE_EXCEPTION;
    private final static QName CALCULARMEDIAIMPLSERVICE_QNAME = new QName("http://servico/", "CalcularMediaImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/servico/?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CALCULARMEDIAIMPLSERVICE_WSDL_LOCATION = url;
        CALCULARMEDIAIMPLSERVICE_EXCEPTION = e;
    }

    public CalcularMediaImplService() {
        super(__getWsdlLocation(), CALCULARMEDIAIMPLSERVICE_QNAME);
    }

    public CalcularMediaImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CALCULARMEDIAIMPLSERVICE_QNAME, features);
    }

    public CalcularMediaImplService(URL wsdlLocation) {
        super(wsdlLocation, CALCULARMEDIAIMPLSERVICE_QNAME);
    }

    public CalcularMediaImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CALCULARMEDIAIMPLSERVICE_QNAME, features);
    }

    public CalcularMediaImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CalcularMediaImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CalcularMedia
     */
    @WebEndpoint(name = "CalcularMediaImplPort")
    public CalcularMedia getCalcularMediaImplPort() {
        return super.getPort(new QName("http://servico/", "CalcularMediaImplPort"), CalcularMedia.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CalcularMedia
     */
    @WebEndpoint(name = "CalcularMediaImplPort")
    public CalcularMedia getCalcularMediaImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://servico/", "CalcularMediaImplPort"), CalcularMedia.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CALCULARMEDIAIMPLSERVICE_EXCEPTION!= null) {
            throw CALCULARMEDIAIMPLSERVICE_EXCEPTION;
        }
        return CALCULARMEDIAIMPLSERVICE_WSDL_LOCATION;
    }

}
